//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCondominio
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelagemContainer : DbContext
    {
        public ModelagemContainer()
            : base("name=ModelagemContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ServicoCodominio> ServicoCodominioSet { get; set; }
        public virtual DbSet<Cidade> CidadeSet { get; set; }
        public virtual DbSet<Apartamento> ApartamentoSet { get; set; }
        public virtual DbSet<Estado> EstadoSet { get; set; }
        public virtual DbSet<Condominio> CondominioSet { get; set; }
        public virtual DbSet<Servico> ServicoSet { get; set; }
        public virtual DbSet<ContaMorador> ContaMoradorSet { get; set; }
        public virtual DbSet<Morador> MoradorSet { get; set; }
        public virtual DbSet<ApartamentoCondominio> ApartamentoCondominioSet { get; set; }
        public virtual DbSet<Usuario> UsuarioSet { get; set; }
    }
}
